// 统一错误码（与 design.md §8.6 对应，后续 checkpoint 逐步补充业务冲突码）。
export const ErrorCodes = {
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  UNAUTHORIZED: 'UNAUTHORIZED',
  FORBIDDEN: 'FORBIDDEN',
  NOT_FOUND: 'NOT_FOUND',
  CONFLICT: 'CONFLICT',
  INTERNAL_ERROR: 'INTERNAL_ERROR',
  DATABASE_UNAVAILABLE: 'DATABASE_UNAVAILABLE',
  AUTH_CONFIGURATION_ERROR: 'AUTH_CONFIGURATION_ERROR',
  MIGRATION_DISABLED: 'MIGRATION_DISABLED',
  MIGRATION_UNAVAILABLE: 'MIGRATION_UNAVAILABLE',
  MIGRATION_FAILED: 'MIGRATION_FAILED',
  // 物品目录 / 图片管线（ck-04）
  BARCODE_CONFLICT: 'BARCODE_CONFLICT',
  FILE_INVALID: 'FILE_INVALID',
  FILE_TOO_LARGE: 'FILE_TOO_LARGE',
  STORAGE_UNAVAILABLE: 'STORAGE_UNAVAILABLE',
  // 发货单（ck-05）
  TRACKING_CONFLICT: 'TRACKING_CONFLICT',
  SHIPMENT_STATE_CONFLICT: 'SHIPMENT_STATE_CONFLICT',
  // 收货点货与差异协商（ck-06）
  COUNTING_STATE_CONFLICT: 'COUNTING_STATE_CONFLICT',
  REVIEW_ALREADY_PROCESSED: 'REVIEW_ALREADY_PROCESSED',
  REVIEW_NO_DIFFERENCE: 'REVIEW_NO_DIFFERENCE',
  // 确认入库与发货退货（ck-07）
  SHIPMENT_NOT_READY: 'SHIPMENT_NOT_READY',
  INBOUND_STATE_CONFLICT: 'INBOUND_STATE_CONFLICT',
  RETURN_STATE_CONFLICT: 'RETURN_STATE_CONFLICT',
  RETURN_ALREADY_PROCESSED: 'RETURN_ALREADY_PROCESSED',
  RETURN_LINE_INVALID: 'RETURN_LINE_INVALID',
  // 库存台账与手动出入库（ck-08a）
  INSUFFICIENT_STOCK: 'INSUFFICIENT_STOCK',
  OUTBOUND_STATE_CONFLICT: 'OUTBOUND_STATE_CONFLICT',
  OUTBOUND_LINE_INVALID: 'OUTBOUND_LINE_INVALID',
  STOCK_BATCH_NOT_FOUND: 'STOCK_BATCH_NOT_FOUND',
  // 销售单（ck-09a）
  SALES_STATE_CONFLICT: 'SALES_STATE_CONFLICT',
  SALES_LINE_INVALID: 'SALES_LINE_INVALID',
} as const;

export type ErrorCode = (typeof ErrorCodes)[keyof typeof ErrorCodes];
