// 统一错误码（与 design.md §8.6 对应，后续 checkpoint 逐步补充业务冲突码）。
export const ErrorCodes = {
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  UNAUTHORIZED: 'UNAUTHORIZED',
  FORBIDDEN: 'FORBIDDEN',
  NOT_FOUND: 'NOT_FOUND',
  CONFLICT: 'CONFLICT',
  INTERNAL_ERROR: 'INTERNAL_ERROR',
  DATABASE_UNAVAILABLE: 'DATABASE_UNAVAILABLE',
  AUTH_CONFIGURATION_ERROR: 'AUTH_CONFIGURATION_ERROR',
  MIGRATION_DISABLED: 'MIGRATION_DISABLED',
  MIGRATION_UNAVAILABLE: 'MIGRATION_UNAVAILABLE',
  MIGRATION_FAILED: 'MIGRATION_FAILED',
  // 物品目录 / 图片管线（ck-04）
  BARCODE_CONFLICT: 'BARCODE_CONFLICT',
  FILE_INVALID: 'FILE_INVALID',
  FILE_TOO_LARGE: 'FILE_TOO_LARGE',
  STORAGE_UNAVAILABLE: 'STORAGE_UNAVAILABLE',
  // 发货单（ck-05）
  TRACKING_CONFLICT: 'TRACKING_CONFLICT',
  SHIPMENT_STATE_CONFLICT: 'SHIPMENT_STATE_CONFLICT',
} as const;

export type ErrorCode = (typeof ErrorCodes)[keyof typeof ErrorCodes];
